### ISSUE TITLE
Removing mods from mod-list.json should delete obsolete zip files

### ISSUE THREAD

**Issue by Fank** [factoriotools/factorio-docker#294]
When you add new mods it works fine, but if you deactivate or delete mods, there are still the downloaded `*.zip` files which causes the server to load them anyways doesn't matter if there are listed in the `mod-list.json` or not.
When a mod is deactivated or not in the list anymore than the zip files in the mods folder should be deleted.

**Comment by frankruegamer** [comment]
The problem is: I don't think that would change anything, if you're automatically updating mods.
I tested this by removing everything from the `mods` folder. When restarting the container all the previous mods would be downloaded.

My guess is that the server is looking at the save file to figure out which mods to download.
In the current state I'm not sure if there is a way to ever remove mods if you're using `UPDATE_MODS_ON_START`.

**Comment by SuperSandro2000** [comment]
This kinda conflicts with #296 and I think it is a bad idea to delete the mod if it is deactivated maybe for debugging or testing something as not always you can grab the zip again.

If you delete the entry Factorio just activates the mod again cause it thinks it is a new mod. Don't think there is a reliable way to differentiate those two.
